// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fboAPI.Data;

namespace fboAPI.Migrations
{
    [DbContext(typeof(LinksContext))]
    [Migration("20181123173152_AddingAgain")]
    partial class AddingAgain
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("fboAPI.Models.CustomerLink", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NewID");

                    b.Property<int>("OldID");

                    b.HasKey("ID");

                    b.ToTable("CustomerLink");
                });
#pragma warning restore 612, 618
        }
    }
}
