// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fboAPI.Data;

namespace fboAPI.Migrations
{
    [DbContext(typeof(LinksContext))]
    [Migration("20181122225747_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("fboAPI.Models.CustomerLink", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NewDataId");

                    b.Property<string>("NewID");

                    b.Property<int?>("OldDataId");

                    b.Property<int>("OldID");

                    b.HasKey("ID");

                    b.HasIndex("NewDataId");

                    b.HasIndex("OldDataId");

                    b.ToTable("CustomerLink");
                });

            modelBuilder.Entity("fboAPI.Models.NewCustomer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("StringsAsString")
                        .IsRequired();

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("NewCustomer");
                });

            modelBuilder.Entity("fboAPI.Models.OldCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("FirstName");

                    b.Property<string>("Surname");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("OldCustomer");
                });

            modelBuilder.Entity("fboAPI.Models.CustomerLink", b =>
                {
                    b.HasOne("fboAPI.Models.NewCustomer", "NewData")
                        .WithMany()
                        .HasForeignKey("NewDataId");

                    b.HasOne("fboAPI.Models.OldCustomer", "OldData")
                        .WithMany()
                        .HasForeignKey("OldDataId");
                });
#pragma warning restore 612, 618
        }
    }
}
